version: '3.5'
services:
  postgres:
    container_name: postgresql_db
    image: postgres:alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123123
      - PGDATA=/data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - novelism-network

  # api:
  #   container_name: novelism-api
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   networks:
  #     - novelism-network

networks:
  novelism-network:
    driver: bridge

volumes:
  postgres:
