## This is a development config file.
# Production config file should be hidden & added to .gitignore

[general]
server = ""

[database]
uri = ""
max_idle_conns = 25
max_open_conns = 2
max_idle_time = "15m"

[jwt]
secret = ""
duration = "48h"
refreshSecret = ""
refreshExpirationDuration = "2w"

[mailer]
host = "smtp-relay.brevo.com"
port = 587
login = ""
password = ""
timeout = ""
