## This is a development config file.
# Production config file should be hidden & added to .gitignore

[general]
server = ""

[logging]
log_header = "${time_rfc3339_nano} [${prefix}][${short_file}][${line}]: ${level}\n"
http_log_format = "${time_rfc3339_nano} - [${remote_ip}][${method}] ${uri} ${status} ${latency_human} (in: ${bytes_in}B, out: ${bytes_out}B) (Error: ${error})\n"

[database]
uri = ""
max_idle_conns = 25
max_open_conns = 2
max_idle_time = "15m"

[jwt]
secret = ""
duration = "48h"

[mailer]
host = "smtp-relay.brevo.com"
port = 587
login = ""
password = ""
timeout = ""
