## This is a development config file.
# Production config file should be hidden & added to .gitignore

[general]
server = ""

[database]
uri = ""

[jwt]
access_ecret = "supersecret"
access_expiration_duration = "48h"

[mailer]
host = "smtp-relay.brevo.com"
port = 587
login = ""
password = ""
timeout = ""
