// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package data

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserStatus string

const (
	UserStatusActive  UserStatus = "active"
	UserStatusIdle    UserStatus = "idle"
	UserStatusDeleted UserStatus = "deleted"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Book struct {
	ID          int32            `json:"id"`
	UserID      pgtype.Int4      `json:"user_id"`
	Title       pgtype.Text      `json:"title"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type Chapter struct {
	ID          int32            `json:"id"`
	BookID      pgtype.Int4      `json:"book_id"`
	AuthorID    pgtype.Int4      `json:"author_id"`
	Title       pgtype.Text      `json:"title"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type ChapterVersion struct {
	ID          int32            `json:"id"`
	ContentID   int32            `json:"content_id"`
	TextContent string           `json:"text_content"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UserID      int32            `json:"user_id"`
}

type Content struct {
	ID          int32            `json:"id"`
	ChapterID   pgtype.Int4      `json:"chapter_id"`
	TextContent pgtype.Text      `json:"text_content"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	DeletedAt   pgtype.Timestamp `json:"deleted_at"`
}

type User struct {
	ID                 int32            `json:"id"`
	Username           string           `json:"username"`
	PasswordHash       string           `json:"password_hash"`
	Email              string           `json:"email"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	Status             NullUserStatus   `json:"status"`
	Verified           pgtype.Bool      `json:"verified"`
	VerificationToken  pgtype.Text      `json:"verification_token"`
	PasswordResetToken pgtype.Text      `json:"password_reset_token"`
	FirstName          pgtype.Text      `json:"first_name"`
	LastName           pgtype.Text      `json:"last_name"`
	DateOfBirth        pgtype.Date      `json:"date_of_birth"`
	Gender             pgtype.Text      `json:"gender"`
	ProfilePicture     pgtype.Text      `json:"profile_picture"`
}
